name: test-readme
run-name: Test README manuals
on:
  push:
    branches:
     - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install depedencies
        # Older pip has some problems with installing tuttest using git url so we have to update it.
        # We have to use venv due to ubuntu `hands-off-system-packages.patch`
        run: python3 -m venv venv/ && source venv/bin/activate && pip install --upgrade pip && pip install '.[dev]'
      - name: Run tests
        run: source venv/bin/activate && .ci-scripts/test.sh
