name: test-readme
run-name: Test README manuals
on:
  push:
    branches:
     - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install depedencies
        run: pip install -e '.[dev]'
      - name: Run tests
        run: .ci-scripts/test.sh
